### ISSUE TITLE
Admin panel E2E testing on netgen servers

### ISSUE THREAD

**Issue by karntrehan** [Samarth-HP/admin-ts#178]

**Comment by aakashyadav-kgp** [comment]
@Nirali010129 to pick admin console testing

**Comment by Nirali010129** [comment]
> @Nirali010129 to pick admin console testing
**BUG LIST**
1. Unable to create location: https://prnt.sc/Nq1235N1gruD
2. The right scroll option is missing on Grade Assessment: https://prnt.sc/cWU0jN9qwAZG
3. The list of E-samwad users is empty even after creating a new user successfully: https://prnt.sc/h_MoHuMSrBY9 https://prnt.sc/ah-P6mcpR6xq
4. Getting Cannot read properties of undefined (reading 'district') error on Shiksha Saathi Users tab:https://prnt.sc/FlYWmxYdnMV7
5. Input validation for mobile number filed while creating E-samwad User: https://prnt.sc/QzD5OMqPPl3P
6. Export feature missing on Grade assessment, E-samwad user, location, tab: https://prnt.sc/BySiMC8j_D7b
7. Input validation for mobile number field while creating Shiksha saathi user: https://prnt.sc/cTzPq0uSqWzr

@aakashyadav-kgp 

cc: @karntrehan

**Comment by choxx** [comment]
@choxx to pick the issues today.

**Comment by choxx** [comment]
@amit-s19 Issues 1) & 3) have been resolved from the backend. The rest of the others are frontend issues. Could you please check?

**Comment by amit-s19** [comment]
Issues Fixed : 
2 -> It's already scrolling
4 -> Fixed in code (https://github.com/Samarth-HP/admin-ts/pull/182)
5 -> Fixed in code (https://github.com/Samarth-HP/admin-ts/pull/182)
6 -> Export wasn't required in these tabs as per requirements
7 -> Mobile validation is already present. It will throw error when you click save.

**Comment by aakashyadav-kgp** [comment]
@Nirali010129 to close testing of fixed bugs today.

**Comment by Nirali010129** [comment]
> @Nirali010129 to close testing of fixed bugs today.
**BUG LIST**
1. Left right scroll option is missing on Grade Assessment: https://prnt.sc/cWU0jN9qwAZG
prnt.sc/ah-P6mcpR6xq
2. Input validation for mobile number filed while creating E-samwad User: https://prnt.sc/QzD5OMqPPl3P
3. Input validation for mobile number field while creating Shiksha saathi user: https://prnt.sc/cTzPq0uSqWzr

These issues are yet to be fixed, please check them out @aakashyadav-kgp @amit-s19 

cc: @karntrehan

**Comment by amit-s19** [comment]
All issues are already fixed @Nirali010129 , attaching videos for the same

Validation of mobile in E - Samwaad
https://github.com/Samarth-HP/admin-ts/assets/46066481/90048a88-2f01-4de0-8496-eaf6660ed696


Validation of mobile in Shiksha Saathi
https://github.com/Samarth-HP/admin-ts/assets/46066481/ce2d68db-8223-455d-94e2-c38a32afd4b1


Scrolling in Grade Assessment
https://github.com/Samarth-HP/admin-ts/assets/46066481/42cfd516-833d-4a9c-8496-5424042dd237

**Comment by Nirali010129** [comment]
> All issues are already fixed @Nirali010129 , attaching videos for the same
> 
> Validation of mobile in E - Samwaad https://github.com/Samarth-HP/admin-ts/assets/46066481/90048a88-2f01-4de0-8496-eaf6660ed696
> 
> Validation of mobile in Shiksha Saathi https://github.com/Samarth-HP/admin-ts/assets/46066481/ce2d68db-8223-455d-94e2-c38a32afd4b1
> 
> Scrolling in Grade Assessment https://github.com/Samarth-HP/admin-ts/assets/46066481/42cfd516-833d-4a9c-8496-5424042dd237

1. Put this limit, the mobile number should not take more than 10 digits
https://www.loom.com/share/df200895a8cb49cba7f5753e5d880ae7?sid=b46f5606-3268-4027-bd0a-6406a66cbea9 
2. When trying to scroll right side in grade assessment, the text is selected 
https://www.loom.com/share/c79c0c357ad1447aae5ac17ad7916b46?sid=155f0c70-9914-493b-adbb-fe4515a81e10
3. Validation of mobile in Shiksha Saathi
https://www.loom.com/share/9c1b36ad72b143d0bf30d71826f3e339?sid=a54f289b-1e78-4757-b632-110cbcd881e3


Hey @amit-s19 Put this limit, the mobile number should not be more than 10 digits and the English alphabet should not be typed in it.
That scrolling feature is working in yours but on my laptop when I go to scroll the text is getting selected, you will be able to see the videos attached to it.

cc : @aakashyadav-kgp @karntrehan

**Comment by amit-s19** [comment]
@Nirali010129 I've fixed the scrolling issue, scrollbars should be visible now allowing you to scroll through the breadth.

As for the other two issues, I cannot put that kind of validation on the input fields due to limitations with underlying React Admin framework.
