### ISSUE TITLE
Editing due to reference is not directly available

### ISSUE THREAD

**Issue by Harshil-Jani** [Samarth-HP/admin-ts#44]
### Description

In the edit component, If there are referenced fields then we have two options, Either we send the NULL update request due to `ReferenceInput` or the other thing is We can redirect it to the particular referenced using `ReferenceField`. 
We need a way to edit the entry directly into the Edit Component. 

#### How to reproduce

![image](https://user-images.githubusercontent.com/79367883/194489817-1ad1a875-39bd-468f-8ca5-a8abc7dd4d64.png)
- Click on `Name` try editing. You will be redirected to `School`

Another Way is 

- Go to `School` click on Edit for any entry and you will see the empty data which may send the NULL value to Hasura on sending `update` request. 

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):
* Browser [e.g. chrome, safari]:

### Logs
 
Any logs (if any) generated in

**Comment by Shruti3004** [comment]
This is resolved! cc: @Harshil-Jani
